spring:
  application:
    name: shop
  datasource:
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "${DB_PASSWORD}"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    database: mysql
  servlet:
    multipart:
      max-file-size: 10MB

server:
  port: 8080
  shutdown: graceful
  tomcat:
    max-http-form-post-size: 10MB
#  servlet:
#    context-path: /home

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: never
  metrics:
    export:
      prometheus:
        enabled: true
